modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/YukkuriC/HexParseMod/issues"
license = "MIT"

[[mods]]
modId = "hexparse"
version = "${version}"
displayName = "HexParse"
authors = "YukkuriC"
description = '''
parse pattern registry name code into list iota, and vice versa
'''
logoFile = "logo.png"
updateJSONURL = "https://api.modrinth.com/updates/WjFyIzFj/forge_updates.json"
displayURL = "https://modrinth.com/mod/hexparse"

[[dependencies.hexparse]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexparse]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexparse]]
modId = "hexcasting"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
